### ISSUE TITLE
Remote Development Implementation Extension

### ISSUE THREAD

**Issue by MarckFp** [lanly-dev/VSCode-LMPTM#2] opened 2019-09-27 15:52 UTC
Your extension seems to be pretty cool, and I love it and wanted to use it asap.

But I have a problem. I use VSCode with Remote Development extensions in a virtual machine with vagrant. So whenever I tried to install this extension, vscode forces me to install it also in the ssh machine where I can't install a chrome/chromium cause it's CLI and without internet access.

There is a way to uses the extension from my local computer with my chrome or it'll try to use the VM alway?

**Comment by lanly-dev** [comment] 2019-09-28 16:35
I see, interesting situation. I found a solution on https://code.visualstudio.com/api/advanced-topics/remote-extensions - they called it "extension kind", so you need to go to add this in your *settings.json*
```json
"remote.extensionKind": {
  "lanly-dev.letmeplaythemusic": "ui"
}
```
![image](https://user-images.githubusercontent.com/14204732/65819503-3cbe5880-e1d2-11e9-8914-91c18b8e4fb5.png)

Thank you for using my extension!

**Comment by MarckFp** [comment] 2019-09-30 07:29
Cool, this indeed "solves" the issue but now the launch button is gone. So I'm not able to execute correctly the extension.

**Comment by lanly-dev** [comment] 2019-09-30 14:40
That is weird, mine does show up.
![image](https://user-images.githubusercontent.com/14204732/65888922-360c1e80-e355-11e9-9f44-25854618c356.png)
![image](https://user-images.githubusercontent.com/14204732/65888854-1674f600-e355-11e9-8ec0-b205fce88f8d.png)

**Comment by MarckFp** [comment] 2019-09-30 15:07
Yes, pretty weird indeed. You can see I have the extension installed locally (I have it in the ssh but disabled) Also I have the extensionKind and no icon found on my bottom bar.

I checked it with the right click on the bottom bar and it didn't even appear the extension name.

Maybe I'm missing something but not sure what.

![image](https://user-images.githubusercontent.com/33698618/65891163-629b5700-e3a4-11e9-8b5c-cb0381592c3c.png)

**Comment by lanly-dev** [comment] 2019-09-30 19:53
hm... I don't really know where to go from here other than basic troubleshoot steps which are reboot OS, restart, reinstall, update vscode/extension and test the setting with another extension.
I can't reproduce this, hence I can't debug this. I tested the setting my extension on Windows and MacOS and it works as expected, are you using it on Linux?
If it still persists, I think it is either your other configurations or other extensions affect the behavior. A bug in my code would be possible, too.

**Comment by lanly-dev** [comment] 2019-10-13 21:29
I am going to close this issue since there is no reply.
I just update this extension so try it out to see if the issue still there.
Feel free to open another one if need to, thanks.

**Closed as completed by lanly-dev** 2019-10-13 21:29 UTC
